authors:
  alfredpersson:
    name: Alfred Persson
    description: Freelance AI Engineer
    avatar: https://avatars.githubusercontent.com/u/alfredpersson
    url: https://www.linkedin.com/in/alfredpersson/
